package models 
type TerraformToBlueprintMapping struct {

	// Compatible versions of Terraform that can be used to execute this configuration.
	CompatibleVersions []string `json:"compatibleVersions"`

	// A reference to the location where the Terraform configuration is being hosted.
	ConfigurationSourceReference *TerraformConfigurationSourceReference `json:"configurationSourceReference,omitempty"`

	// Information about output values generated by the Terraform configuration.
	OutputValues []*OutputValue `json:"outputValues"`

	// Information about providers used in the Terraform configuration.
	Providers []*Provider `json:"providers"`

	// Information about variables expected by the Terraform configuration.
	Variables []*Variable `json:"variables"`

	// A list of warnings related to the Terraform configuration.
	Warnings []string `json:"warnings"`
}

