/*
Copyright 2023 Upbound Inc. - ANKASOFT
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type DeploymentObservation struct {

	// The content of the the cloud template to be used to request the deployment.
	BlueprintContent *string `json:"blueprintContent,omitempty" tf:"blueprint_content,omitempty"`

	// The id of the cloud template to be used to request the deployment.
	BlueprintID *string `json:"blueprintId,omitempty" tf:"blueprint_id,omitempty"`

	// The version of the cloud template to be used to request the deployment.
	BlueprintVersion *string `json:"blueprintVersion,omitempty" tf:"blueprint_version,omitempty"`

	// The id of the catalog item to be used to request the deployment.
	CatalogItemID *string `json:"catalogItemId,omitempty" tf:"catalog_item_id,omitempty"`

	// The version of the catalog item to be used to request the deployment.
	CatalogItemVersion *string `json:"catalogItemVersion,omitempty" tf:"catalog_item_version,omitempty"`

	// Date when the entity was created. The date is in ISO 6801 and UTC.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// The user the entity was created by.
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// A human-friendly description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ExpandLastRequest *bool `json:"expandLastRequest,omitempty" tf:"expand_last_request,omitempty"`

	// Flag to indicate whether to expand project information.
	ExpandProject *bool `json:"expandProject,omitempty" tf:"expand_project,omitempty"`

	ExpandResources *bool `json:"expandResources,omitempty" tf:"expand_resources,omitempty"`

	Expense []ExpenseObservation `json:"expense,omitempty" tf:"expense,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Inputs provided by the user. For inputs including those with default values, refer to inputs_including_defaults.
	Inputs map[string]*string `json:"inputs,omitempty" tf:"inputs,omitempty"`

	// All the inputs applied during last create/update operation, including those with default values.
	InputsIncludingDefaults map[string]*string `json:"inputsIncludingDefaults,omitempty" tf:"inputs_including_defaults,omitempty"`

	LastRequest []LastRequestObservation `json:"lastRequest,omitempty" tf:"last_request,omitempty"`

	// Date when the entity was last updated. The date is in ISO 6801 and UTC.
	LastUpdatedAt *string `json:"lastUpdatedAt,omitempty" tf:"last_updated_at,omitempty"`

	// The user that last updated the deployment.
	LastUpdatedBy *string `json:"lastUpdatedBy,omitempty" tf:"last_updated_by,omitempty"`

	// Date when the deployment lease expire. The date is in ISO 6801 and UTC.
	LeaseExpireAt *string `json:"leaseExpireAt,omitempty" tf:"lease_expire_at,omitempty"`

	// The name of the deployment.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The Id of the organization this deployment belongs to.
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// The user this deployment belongs to.
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	Project []ProjectObservation `json:"project,omitempty" tf:"project,omitempty"`

	// The id of the project this deployment belongs to.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reason for requesting/updating a blueprint.
	Reason *string `json:"reason,omitempty" tf:"reason,omitempty"`

	Resources []ResourcesObservation `json:"resources,omitempty" tf:"resources,omitempty"`

	// The status of the deployment with respect to its life cycle operations.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type DeploymentParameters struct {

	// The content of the the cloud template to be used to request the deployment.
	// +kubebuilder:validation:Optional
	BlueprintContent *string `json:"blueprintContent,omitempty" tf:"blueprint_content,omitempty"`

	// The id of the cloud template to be used to request the deployment.
	// +kubebuilder:validation:Optional
	BlueprintID *string `json:"blueprintId,omitempty" tf:"blueprint_id,omitempty"`

	// The version of the cloud template to be used to request the deployment.
	// +kubebuilder:validation:Optional
	BlueprintVersion *string `json:"blueprintVersion,omitempty" tf:"blueprint_version,omitempty"`

	// The id of the catalog item to be used to request the deployment.
	// +kubebuilder:validation:Optional
	CatalogItemID *string `json:"catalogItemId,omitempty" tf:"catalog_item_id,omitempty"`

	// The version of the catalog item to be used to request the deployment.
	// +kubebuilder:validation:Optional
	CatalogItemVersion *string `json:"catalogItemVersion,omitempty" tf:"catalog_item_version,omitempty"`

	// A human-friendly description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// +kubebuilder:validation:Optional
	ExpandLastRequest *bool `json:"expandLastRequest,omitempty" tf:"expand_last_request,omitempty"`

	// Flag to indicate whether to expand project information.
	// +kubebuilder:validation:Optional
	ExpandProject *bool `json:"expandProject,omitempty" tf:"expand_project,omitempty"`

	// +kubebuilder:validation:Optional
	ExpandResources *bool `json:"expandResources,omitempty" tf:"expand_resources,omitempty"`

	// Inputs provided by the user. For inputs including those with default values, refer to inputs_including_defaults.
	// +kubebuilder:validation:Optional
	Inputs map[string]*string `json:"inputs,omitempty" tf:"inputs,omitempty"`

	// The name of the deployment.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The user this deployment belongs to.
	// +kubebuilder:validation:Optional
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// The id of the project this deployment belongs to.
	// +crossplane:generate:reference:type=github.com/ankasoftco/provider-vra/apis/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// Reason for requesting/updating a blueprint.
	// +kubebuilder:validation:Optional
	Reason *string `json:"reason,omitempty" tf:"reason,omitempty"`
}

type ExpenseObservation struct {
	AdditionalExpense *float64 `json:"additionalExpense,omitempty" tf:"additional_expense,omitempty"`

	Code *string `json:"code,omitempty" tf:"code,omitempty"`

	ComputeExpense *float64 `json:"computeExpense,omitempty" tf:"compute_expense,omitempty"`

	LastUpdateTime *string `json:"lastUpdateTime,omitempty" tf:"last_update_time,omitempty"`

	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	NetworkExpense *float64 `json:"networkExpense,omitempty" tf:"network_expense,omitempty"`

	StorageExpense *float64 `json:"storageExpense,omitempty" tf:"storage_expense,omitempty"`

	TotalExpense *float64 `json:"totalExpense,omitempty" tf:"total_expense,omitempty"`

	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`
}

type ExpenseParameters struct {
}

type LastRequestObservation struct {
	ActionID *string `json:"actionId,omitempty" tf:"action_id,omitempty"`

	ApprovedAt *string `json:"approvedAt,omitempty" tf:"approved_at,omitempty"`

	BlueprintID *string `json:"blueprintId,omitempty" tf:"blueprint_id,omitempty"`

	Cancelable *bool `json:"cancelable,omitempty" tf:"cancelable,omitempty"`

	CatalogItemID *string `json:"catalogItemId,omitempty" tf:"catalog_item_id,omitempty"`

	CompletedAt *string `json:"completedAt,omitempty" tf:"completed_at,omitempty"`

	CompletedTasks *float64 `json:"completedTasks,omitempty" tf:"completed_tasks,omitempty"`

	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	Details *string `json:"details,omitempty" tf:"details,omitempty"`

	Dismissed *bool `json:"dismissed,omitempty" tf:"dismissed,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	InitializedAt *string `json:"initializedAt,omitempty" tf:"initialized_at,omitempty"`

	Inputs map[string]*string `json:"inputs,omitempty" tf:"inputs,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Outputs map[string]*string `json:"outputs,omitempty" tf:"outputs,omitempty"`

	RequestedBy *string `json:"requestedBy,omitempty" tf:"requested_by,omitempty"`

	ResourceIds []*string `json:"resourceIds,omitempty" tf:"resource_ids,omitempty"`

	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	TotalTasks *float64 `json:"totalTasks,omitempty" tf:"total_tasks,omitempty"`

	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type LastRequestParameters struct {
}

type ProjectObservation struct {
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type ProjectParameters struct {
}

type ResourcesExpenseObservation struct {
	AdditionalExpense *float64 `json:"additionalExpense,omitempty" tf:"additional_expense,omitempty"`

	Code *string `json:"code,omitempty" tf:"code,omitempty"`

	ComputeExpense *float64 `json:"computeExpense,omitempty" tf:"compute_expense,omitempty"`

	LastUpdateTime *string `json:"lastUpdateTime,omitempty" tf:"last_update_time,omitempty"`

	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	NetworkExpense *float64 `json:"networkExpense,omitempty" tf:"network_expense,omitempty"`

	StorageExpense *float64 `json:"storageExpense,omitempty" tf:"storage_expense,omitempty"`

	TotalExpense *float64 `json:"totalExpense,omitempty" tf:"total_expense,omitempty"`

	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`
}

type ResourcesExpenseParameters struct {
}

type ResourcesObservation struct {
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	DependsOn []*string `json:"dependsOn,omitempty" tf:"depends_on,omitempty"`

	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	Expense []ResourcesExpenseObservation `json:"expense,omitempty" tf:"expense,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	PropertiesJSON *string `json:"propertiesJson,omitempty" tf:"properties_json,omitempty"`

	State *string `json:"state,omitempty" tf:"state,omitempty"`

	SyncStatus *string `json:"syncStatus,omitempty" tf:"sync_status,omitempty"`

	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ResourcesParameters struct {
}

// DeploymentSpec defines the desired state of Deployment
type DeploymentSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DeploymentParameters `json:"forProvider"`
}

// DeploymentStatus defines the observed state of Deployment.
type DeploymentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DeploymentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Deployment is the Schema for the Deployments API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vra}
type Deployment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.name)",message="name is a required parameter"
	Spec   DeploymentSpec   `json:"spec"`
	Status DeploymentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DeploymentList contains a list of Deployments
type DeploymentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Deployment `json:"items"`
}

// Repository type metadata.
var (
	Deployment_Kind             = "Deployment"
	Deployment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Deployment_Kind}.String()
	Deployment_KindAPIVersion   = Deployment_Kind + "." + CRDGroupVersion.String()
	Deployment_GroupVersionKind = CRDGroupVersion.WithKind(Deployment_Kind)
)

func init() {
	SchemeBuilder.Register(&Deployment{}, &DeploymentList{})
}
