/*
Copyright 2023 Upbound Inc. - ANKASOFT
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ProfileVsphereLinksObservation struct {
	Href *string `json:"href,omitempty" tf:"href,omitempty"`

	Hrefs []*string `json:"hrefs,omitempty" tf:"hrefs,omitempty"`

	Rel *string `json:"rel,omitempty" tf:"rel,omitempty"`
}

type ProfileVsphereLinksParameters struct {
}

type ProfileVsphereObservation struct {

	// Id of the cloud account this storage profile belongs to.
	CloudAccountID *string `json:"cloudAccountId,omitempty" tf:"cloud_account_id,omitempty"`

	// Date when the entity was created. The date is in ISO 8601 and UTC.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Id of the vSphere Datastore for placing disk and VM.
	DatastoreID *string `json:"datastoreId,omitempty" tf:"datastore_id,omitempty"`

	// Indicates if a storage profile acts as a default storage profile for a disk.
	DefaultItem *bool `json:"defaultItem,omitempty" tf:"default_item,omitempty"`

	// A human-friendly description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Type of mode for the disk. Omitting this value will set it to dependent. example: dependent / independent-persistent / independent-nonpersistent.
	DiskMode *string `json:"diskMode,omitempty" tf:"disk_mode,omitempty"`

	// Disk types are specified as standard or first class, empty value is considered as standard.
	DiskType *string `json:"diskType,omitempty" tf:"disk_type,omitempty"`

	// The id of the region for which this profile is defined
	ExternalRegionID *string `json:"externalRegionId,omitempty" tf:"external_region_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The upper bound for the I/O operations per second allocated for each virtual disk.
	LimitIops *string `json:"limitIops,omitempty" tf:"limit_iops,omitempty"`

	Links []ProfileVsphereLinksObservation `json:"links,omitempty" tf:"links,omitempty"`

	// A human-friendly name used as an identifier in APIs that support this option.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The id of the organization this entity belongs to.
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Email of the user that owns the entity.
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// Type of provisioning policy for the disk.
	ProvisioningType *string `json:"provisioningType,omitempty" tf:"provisioning_type,omitempty"`

	// The Id of the region that is associated with the storage profile.
	RegionID *string `json:"regionId,omitempty" tf:"region_id,omitempty"`

	// A specific number of shares assigned to each virtual machine.
	Shares *string `json:"shares,omitempty" tf:"shares,omitempty"`

	// Indicates whether this storage profile supports encryption or not.
	SharesLevel *string `json:"sharesLevel,omitempty" tf:"shares_level,omitempty"`

	// Id of the vSphere Storage Policy to be applied.
	StoragePolicyID *string `json:"storagePolicyId,omitempty" tf:"storage_policy_id,omitempty"`

	// Indicates whether this storage profile supports encryption or not.
	SupportsEncryption *bool `json:"supportsEncryption,omitempty" tf:"supports_encryption,omitempty"`

	Tags []ProfileVsphereTagsObservation `json:"tags,omitempty" tf:"tags,omitempty"`

	// Date when the entity was last updated. The date is ISO 8601 and UTC.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type ProfileVsphereParameters struct {

	// Id of the vSphere Datastore for placing disk and VM.
	// +kubebuilder:validation:Optional
	DatastoreID *string `json:"datastoreId,omitempty" tf:"datastore_id,omitempty"`

	// Indicates if a storage profile acts as a default storage profile for a disk.
	// +kubebuilder:validation:Optional
	DefaultItem *bool `json:"defaultItem,omitempty" tf:"default_item,omitempty"`

	// A human-friendly description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Type of mode for the disk. Omitting this value will set it to dependent. example: dependent / independent-persistent / independent-nonpersistent.
	// +kubebuilder:validation:Optional
	DiskMode *string `json:"diskMode,omitempty" tf:"disk_mode,omitempty"`

	// Disk types are specified as standard or first class, empty value is considered as standard.
	// +kubebuilder:validation:Optional
	DiskType *string `json:"diskType,omitempty" tf:"disk_type,omitempty"`

	// The upper bound for the I/O operations per second allocated for each virtual disk.
	// +kubebuilder:validation:Optional
	LimitIops *string `json:"limitIops,omitempty" tf:"limit_iops,omitempty"`

	// A human-friendly name used as an identifier in APIs that support this option.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Type of provisioning policy for the disk.
	// +kubebuilder:validation:Optional
	ProvisioningType *string `json:"provisioningType,omitempty" tf:"provisioning_type,omitempty"`

	// The Id of the region that is associated with the storage profile.
	// +kubebuilder:validation:Optional
	RegionID *string `json:"regionId,omitempty" tf:"region_id,omitempty"`

	// A specific number of shares assigned to each virtual machine.
	// +kubebuilder:validation:Optional
	Shares *string `json:"shares,omitempty" tf:"shares,omitempty"`

	// Indicates whether this storage profile supports encryption or not.
	// +kubebuilder:validation:Optional
	SharesLevel *string `json:"sharesLevel,omitempty" tf:"shares_level,omitempty"`

	// Id of the vSphere Storage Policy to be applied.
	// +kubebuilder:validation:Optional
	StoragePolicyID *string `json:"storagePolicyId,omitempty" tf:"storage_policy_id,omitempty"`

	// Indicates whether this storage profile supports encryption or not.
	// +kubebuilder:validation:Optional
	SupportsEncryption *bool `json:"supportsEncryption,omitempty" tf:"supports_encryption,omitempty"`

	// +kubebuilder:validation:Optional
	Tags []ProfileVsphereTagsParameters `json:"tags,omitempty" tf:"tags,omitempty"`
}

type ProfileVsphereTagsObservation struct {
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ProfileVsphereTagsParameters struct {

	// +kubebuilder:validation:Required
	Key *string `json:"key" tf:"key,omitempty"`

	// +kubebuilder:validation:Required
	Value *string `json:"value" tf:"value,omitempty"`
}

// ProfileVsphereSpec defines the desired state of ProfileVsphere
type ProfileVsphereSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ProfileVsphereParameters `json:"forProvider"`
}

// ProfileVsphereStatus defines the observed state of ProfileVsphere.
type ProfileVsphereStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ProfileVsphereObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// ProfileVsphere is the Schema for the ProfileVspheres API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vra}
type ProfileVsphere struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.defaultItem)",message="defaultItem is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.name)",message="name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.regionId)",message="regionId is a required parameter"
	Spec   ProfileVsphereSpec   `json:"spec"`
	Status ProfileVsphereStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProfileVsphereList contains a list of ProfileVspheres
type ProfileVsphereList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ProfileVsphere `json:"items"`
}

// Repository type metadata.
var (
	ProfileVsphere_Kind             = "ProfileVsphere"
	ProfileVsphere_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ProfileVsphere_Kind}.String()
	ProfileVsphere_KindAPIVersion   = ProfileVsphere_Kind + "." + CRDGroupVersion.String()
	ProfileVsphere_GroupVersionKind = CRDGroupVersion.WithKind(ProfileVsphere_Kind)
)

func init() {
	SchemeBuilder.Register(&ProfileVsphere{}, &ProfileVsphereList{})
}
