/*
Copyright 2023 Upbound Inc. - ANKASOFT
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type NetworkIPRangeLinksObservation struct {
	Href *string `json:"href,omitempty" tf:"href,omitempty"`

	Hrefs []*string `json:"hrefs,omitempty" tf:"hrefs,omitempty"`

	Rel *string `json:"rel,omitempty" tf:"rel,omitempty"`
}

type NetworkIPRangeLinksParameters struct {
}

type NetworkIPRangeObservation struct {

	// Date when the entity was created. The date is in ISO 8601 and UTC.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// A human-friendly description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// End IP address of the range.
	EndIPAddress *string `json:"endIpAddress,omitempty" tf:"end_ip_address,omitempty"`

	// External entity Id on the provider side.
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`

	// The Id of the fabric network.
	FabricNetworkID *string `json:"fabricNetworkId,omitempty" tf:"fabric_network_id,omitempty"`

	// The Ids of the fabric networks.
	FabricNetworkIds []*string `json:"fabricNetworkIds,omitempty" tf:"fabric_network_ids,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// IP address version: IPv4 or IPv6.
	IPVersion *string `json:"ipVersion,omitempty" tf:"ip_version,omitempty"`

	Links []NetworkIPRangeLinksObservation `json:"links,omitempty" tf:"links,omitempty"`

	// The name of the network IP range.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The id of the organization this entity belongs to.
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Email of the user that owns the entity.
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// Start IP address of the range.
	StartIPAddress *string `json:"startIpAddress,omitempty" tf:"start_ip_address,omitempty"`

	Tags []NetworkIPRangeTagsObservation `json:"tags,omitempty" tf:"tags,omitempty"`

	// Date when the entity was last updated. The date is ISO 8601 and UTC.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type NetworkIPRangeParameters struct {

	// A human-friendly description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// End IP address of the range.
	// +kubebuilder:validation:Optional
	EndIPAddress *string `json:"endIpAddress,omitempty" tf:"end_ip_address,omitempty"`

	// The Id of the fabric network.
	// +kubebuilder:validation:Optional
	FabricNetworkID *string `json:"fabricNetworkId,omitempty" tf:"fabric_network_id,omitempty"`

	// The Ids of the fabric networks.
	// +kubebuilder:validation:Optional
	FabricNetworkIds []*string `json:"fabricNetworkIds,omitempty" tf:"fabric_network_ids,omitempty"`

	// IP address version: IPv4 or IPv6.
	// +kubebuilder:validation:Optional
	IPVersion *string `json:"ipVersion,omitempty" tf:"ip_version,omitempty"`

	// The name of the network IP range.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Start IP address of the range.
	// +kubebuilder:validation:Optional
	StartIPAddress *string `json:"startIpAddress,omitempty" tf:"start_ip_address,omitempty"`

	// +kubebuilder:validation:Optional
	Tags []NetworkIPRangeTagsParameters `json:"tags,omitempty" tf:"tags,omitempty"`
}

type NetworkIPRangeTagsObservation struct {
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type NetworkIPRangeTagsParameters struct {

	// +kubebuilder:validation:Required
	Key *string `json:"key" tf:"key,omitempty"`

	// +kubebuilder:validation:Required
	Value *string `json:"value" tf:"value,omitempty"`
}

// NetworkIPRangeSpec defines the desired state of NetworkIPRange
type NetworkIPRangeSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     NetworkIPRangeParameters `json:"forProvider"`
}

// NetworkIPRangeStatus defines the observed state of NetworkIPRange.
type NetworkIPRangeStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NetworkIPRangeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkIPRange is the Schema for the NetworkIPRanges API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vra}
type NetworkIPRange struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.endIpAddress)",message="endIpAddress is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.ipVersion)",message="ipVersion is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.name)",message="name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.startIpAddress)",message="startIpAddress is a required parameter"
	Spec   NetworkIPRangeSpec   `json:"spec"`
	Status NetworkIPRangeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkIPRangeList contains a list of NetworkIPRanges
type NetworkIPRangeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkIPRange `json:"items"`
}

// Repository type metadata.
var (
	NetworkIPRange_Kind             = "NetworkIPRange"
	NetworkIPRange_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NetworkIPRange_Kind}.String()
	NetworkIPRange_KindAPIVersion   = NetworkIPRange_Kind + "." + CRDGroupVersion.String()
	NetworkIPRange_GroupVersionKind = CRDGroupVersion.WithKind(NetworkIPRange_Kind)
)

func init() {
	SchemeBuilder.Register(&NetworkIPRange{}, &NetworkIPRangeList{})
}
