/*
Copyright 2023 Upbound Inc. - ANKASOFT
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AccountVmcLinksObservation struct {
	Href *string `json:"href,omitempty" tf:"href,omitempty"`

	Hrefs []*string `json:"hrefs,omitempty" tf:"hrefs,omitempty"`

	Rel *string `json:"rel,omitempty" tf:"rel,omitempty"`
}

type AccountVmcLinksParameters struct {
}

type AccountVmcObservation struct {
	APIToken *string `json:"apiToken,omitempty" tf:"api_token,omitempty"`

	// Whether to accept self signed certificate when connecting to the vCenter Server.
	AcceptSelfSignedCert *bool `json:"acceptSelfSignedCert,omitempty" tf:"accept_self_signed_cert,omitempty"`

	// Date when the entity was created. The date is in ISO 8601 and UTC.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Identifier of a data collector vm deployed in the on premise infrastructure.
	DcID *string `json:"dcId,omitempty" tf:"dc_id,omitempty"`

	// A human-friendly description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Links []AccountVmcLinksObservation `json:"links,omitempty" tf:"links,omitempty"`

	// The name of this resource instance.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	NsxHostname *string `json:"nsxHostname,omitempty" tf:"nsx_hostname,omitempty"`

	// The id of the organization this entity belongs to.
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Email of the user that owns the entity.
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// The set of region ids that will be enabled for this cloud account.
	Regions []*string `json:"regions,omitempty" tf:"regions,omitempty"`

	SddcName *string `json:"sddcName,omitempty" tf:"sddc_name,omitempty"`

	Tags []AccountVmcTagsObservation `json:"tags,omitempty" tf:"tags,omitempty"`

	// Date when the entity was last updated. The date is ISO 8601 and UTC.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	VcenterHostname *string `json:"vcenterHostname,omitempty" tf:"vcenter_hostname,omitempty"`

	VcenterUsername *string `json:"vcenterUsername,omitempty" tf:"vcenter_username,omitempty"`
}

type AccountVmcParameters struct {

	// +kubebuilder:validation:Optional
	APIToken *string `json:"apiToken,omitempty" tf:"api_token,omitempty"`

	// Whether to accept self signed certificate when connecting to the vCenter Server.
	// +kubebuilder:validation:Optional
	AcceptSelfSignedCert *bool `json:"acceptSelfSignedCert,omitempty" tf:"accept_self_signed_cert,omitempty"`

	// Identifier of a data collector vm deployed in the on premise infrastructure.
	// +kubebuilder:validation:Optional
	DcID *string `json:"dcId,omitempty" tf:"dc_id,omitempty"`

	// A human-friendly description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The name of this resource instance.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	NsxHostname *string `json:"nsxHostname,omitempty" tf:"nsx_hostname,omitempty"`

	// The set of region ids that will be enabled for this cloud account.
	// +kubebuilder:validation:Optional
	Regions []*string `json:"regions,omitempty" tf:"regions,omitempty"`

	// +kubebuilder:validation:Optional
	SddcName *string `json:"sddcName,omitempty" tf:"sddc_name,omitempty"`

	// +kubebuilder:validation:Optional
	Tags []AccountVmcTagsParameters `json:"tags,omitempty" tf:"tags,omitempty"`

	// +kubebuilder:validation:Optional
	VcenterHostname *string `json:"vcenterHostname,omitempty" tf:"vcenter_hostname,omitempty"`

	// +kubebuilder:validation:Optional
	VcenterPasswordSecretRef v1.SecretKeySelector `json:"vcenterPasswordSecretRef" tf:"-"`

	// +kubebuilder:validation:Optional
	VcenterUsername *string `json:"vcenterUsername,omitempty" tf:"vcenter_username,omitempty"`
}

type AccountVmcTagsObservation struct {
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type AccountVmcTagsParameters struct {

	// +kubebuilder:validation:Required
	Key *string `json:"key" tf:"key,omitempty"`

	// +kubebuilder:validation:Required
	Value *string `json:"value" tf:"value,omitempty"`
}

// AccountVmcSpec defines the desired state of AccountVmc
type AccountVmcSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AccountVmcParameters `json:"forProvider"`
}

// AccountVmcStatus defines the observed state of AccountVmc.
type AccountVmcStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AccountVmcObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// AccountVmc is the Schema for the AccountVmcs API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vra}
type AccountVmc struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.apiToken)",message="apiToken is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.name)",message="name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.nsxHostname)",message="nsxHostname is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.regions)",message="regions is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.sddcName)",message="sddcName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.vcenterHostname)",message="vcenterHostname is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.vcenterPasswordSecretRef)",message="vcenterPasswordSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.vcenterUsername)",message="vcenterUsername is a required parameter"
	Spec   AccountVmcSpec   `json:"spec"`
	Status AccountVmcStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountVmcList contains a list of AccountVmcs
type AccountVmcList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountVmc `json:"items"`
}

// Repository type metadata.
var (
	AccountVmc_Kind             = "AccountVmc"
	AccountVmc_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountVmc_Kind}.String()
	AccountVmc_KindAPIVersion   = AccountVmc_Kind + "." + CRDGroupVersion.String()
	AccountVmc_GroupVersionKind = CRDGroupVersion.WithKind(AccountVmc_Kind)
)

func init() {
	SchemeBuilder.Register(&AccountVmc{}, &AccountVmcList{})
}
