apiVersion: vra.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  baseUrl: "https://api.mgmt.cloud.vmware.com"
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: provider-vra-secret
      key: credentials
