---
apiVersion: vraprovider.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  baseUrl: 
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: vra-provider-secret
      key: credentials
