---
apiVersion: vraprovider.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  baseUrl: api.mgmt.cloud.vmware.com
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: example-provider-secret
      key: credentials
