apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: provider-vra-secret
type: Opaque
stringData:
  credentials: "VsOjDsnHvofWvj63QTNjdBYKqy5lb3fb1wo4kDQUJbWWfFGmB83UCm4vBNJWPkpw"