apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: provider-vra-secret-allianznext
type: Opaque
stringData:
  credentials: "PBliQNx-NEGdqh785Ms1aM10BjzKSzbLzvS7_fmn8xFyVY_2KuiN48DfkKxTQ6AA"